version: '3'

services:

  database:
    image: postgres
    container_name: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=flask-shop
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123
    hostname: database

  backend:
    container_name: flask
    build:
      context: .
    depends_on:
      - database
    ports:
      - "5000:5000"

  celery_worker:
    build: .
    environment:
      - POSTGRES_PASSWORD=123
      - DB_HOSTNAME:db
      - DB_NAME=flask-shop
      - DB_USERNAME=postgres
      - DB_PASSWORD=123
      - RABBIT_HOST=message_queue
    depends_on:
      - database
      - message_queue
    command: celery -A our_celery.send_email --loglevel=INFO --purge --pool=solo

  message_queue:
    image: rabbitmq:3-management
    ports:
      - 5672:5672
      - 15672:15672
    hostname: message_queue