"""add compare_list table

Revision ID: 2e20c099f260
Revises: e519ddd16ab8
Create Date: 2024-01-28 03:23:41.777063

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2e20c099f260'
down_revision: Union[str, None] = 'e519ddd16ab8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('compare_list',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_login', sa.String(length=32), nullable=True),
    sa.Column('item_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['item_id'], ['item.id'], ),
    sa.ForeignKeyConstraint(['user_login'], ['user.login'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('compare_list')
    # ### end Alembic commands ###
